task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

num_classes: 80
remap_mscoco_category: True

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: ../datasets/coco/images/train2017/
    ann_file: ../datasets/coco/annotations/instances_train2017.json
    
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 4
  drop_last: True
  collate_fn:
    type: BatchImageCollateFunction # check this!
  


val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: ../datasets/coco/images/val2017/
    ann_file: ../datasets/coco/annotations/instances_val2017.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: False
  num_workers: 4
  drop_last: False
  collate_fn:
    type: BatchImageCollateFunction
