use_amp: True
use_ema: True
ema:
  type: ModelEMA
  decay: 0.9999
  warmups: 2000
  start: 0


epoches: 72
clip_max_norm: 0.1


optimizer:
  type: AdamW
  params:
    -
      # including backbone, but not norm
      params: '^(?=.*backbone)(?!.*norm).*$'
      lr: 0.0000063 # Backbone LR
    -
      # ^(?=.*A)(?=.*B).*$ including a and b
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn)).*$'
      weight_decay: 0.

  lr: 0.000125  # Base LR 
  betas: [0.9, 0.999]
  weight_decay: 0.000125


lr_scheduler:
  type: MultiStepLR
  milestones: [500]
  gamma: 0.1

lr_warmup_scheduler:
  type: LinearWarmup
  warmup_duration: 1000
